import heroTryOn from "@/assets/hero-tryon.jpg";
import tryOnProduct from "@/assets/tryon-product.jpg";

import { AgentMark, Chip, Tag, Wordmark } from "./kit";
import { Phone } from "./phone";
import { WaitlistForm } from "./waitlist-form";

export function Hero() {
  return (
    <section className="relative overflow-hidden">
      <div className="mx-auto grid w-full max-w-6xl grid-cols-1 items-center gap-14 px-5 pt-16 pb-20 sm:px-8 sm:pt-24 sm:pb-28 lg:grid-cols-[1.05fr_0.95fr]">
        <div>
          <span className="inline-flex items-center gap-2 rounded-full border border-border-agent bg-agent px-3 py-1 text-[12px] font-medium text-agent-foreground">
            <AgentMark size={13} />
            Private beta — early access
          </span>

          <h1 className="mt-6 text-[clamp(2.75rem,7vw,5.5rem)] leading-[1.04] font-bold tracking-[var(--tracking-display)]">
            <Wordmark className="text-signal-ink" />, where shopping is about you
          </h1>

          <p className="mt-6 max-w-[52ch] text-[17px] leading-[1.6] text-secondary-foreground">
            apt is a personal shopping agent that learns your taste, finds the
            pieces worth your attention, and shows you how each one actually looks
            on you — before you spend anything.
          </p>

          <div className="mt-8 max-w-lg">
            <WaitlistForm id="hero-email" size="lg" />
          </div>

          <div className="mt-4 flex flex-wrap gap-2">
            <Chip active>See it on you</Chip>
            <Chip>Clothes, shoes, bags</Chip>
            <Chip>No feed of strangers</Chip>
          </div>
        </div>

        <div className="relative mx-auto flex w-full justify-center">
          <div
            aria-hidden="true"
            className="absolute top-1/2 left-1/2 -z-10 h-[420px] w-[420px] -translate-x-1/2 -translate-y-1/2 rounded-full bg-signal-wash blur-3xl"
          />
          <Phone>
            <img
              src={heroTryOn}
              alt="A shopper shown wearing a cream wool coat generated by apt"
              width={896}
              height={1152}
              className="h-full w-full object-cover"
            />
            <div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-grey-10/60 to-transparent p-4 pt-14">
              <div className="flex items-center justify-between gap-3 rounded-xl bg-card/95 p-3 backdrop-blur">
                <img
                  src={tryOnProduct}
                  alt="Cream wool coat product shot"
                  width={896}
                  height={1152}
                  loading="lazy"
                  className="h-11 w-11 rounded-md object-cover"
                />
                <div className="min-w-0 flex-1">
                  <p className="truncate text-[13px] font-medium">
                    Oversized wool coat
                  </p>
                  <p className="text-[12px] text-muted-foreground">$248</p>
                </div>
                <Tag tone="agent">96% match</Tag>
              </div>
            </div>
          </Phone>
        </div>
      </div>
    </section>
  );
}
